# Global values available to all charts
global:
  # Set environment: "minikube" or "aks"
  environment: "minikube"
  logMaxLineLength: 10240
  orchestratorImage:
    repository: ghcr.io/trailofbits/buttercup/buttercup-orchestrator
    tag: "main"
    pullPolicy: Always
    pullSecrets: ["ghcr-auth"]
  fuzzerImage:
    repository: ghcr.io/trailofbits/buttercup/buttercup-fuzzer
    tag: "main"
    pullPolicy: Always
    pullSecrets: ["ghcr-auth"]
  seedGenImage:
    repository: ghcr.io/trailofbits/buttercup/buttercup-seed-gen
    tag: "main"
    pullPolicy: Always
    pullSecrets: ["ghcr-auth"]
  patcherImage:
    repository: ghcr.io/trailofbits/buttercup/buttercup-patcher
    tag: "main"
    pullPolicy: Always
    pullSecrets: ["ghcr-auth"]
  programModelImage:
    repository: ghcr.io/trailofbits/buttercup/buttercup-program-model
    tag: "main"
    pullPolicy: Always
    pullSecrets: ["ghcr-auth"]
  competitionApiImage:
    repository: ghcr.io/tob-challenges/example-crs-architecture/competition-test-api
    tag: v1.4-rc1
    pullPolicy: Always
    pullSecrets: ["ghcr-auth"]

  # Default sample size for the coverage bot
  coverageBot:
    sampleSize: 200

  # Max PoV size limit
  maxPovSize: 2097152  # 2 MiB

  # Langfuse global configuration for all subcharts
  langfuse:
    enabled: false
    host: "https://cloud.langfuse.com"
    publicKey: "pk-lf-..."  # Replace with your actual public key
    secretKey: "sk-lf-..."  # Replace with your actual secret key
  signoz:
    deployed: false
  crs:
    api_key_id: 515cc8a0-3019-4c9f-8c1c-72d0b54ae561
    api_key_token: VGuAC8axfOnFXKBB7irpNDOKcDjOlnyB
    api_key_token_hash: "$argon2id$v=19$m=65536,t=3,p=4$Dg1v6NPGTyXPoOPF4ozD5A$wa/85ttk17bBsIASSwdR/uGz5UKN/bZuu4wu+JIy1iA"
    # api_url: "https://api.tail7e9b4c.ts.net"
    hostname: "buttercup-crs"
    competition_api_key_id: 11111111-1111-1111-1111-111111111111
    competition_api_key_token: secret
    # competition_api_url: "https://api.tail7e9b4c.ts.net"
  otel:
    endpoint: "https://127.0.0.1:4318" # TODO: Change to the actual endpoint
    token: "token"
    protocol: "grpc"
  queueTimeouts:
    buildTaskTimeoutMs: 120000
    buildOutputTaskTimeoutMs: 120000
    downloadTaskTimeoutMs: 120000
    readyTaskTimeoutMs: 120000
    deleteTaskTimeoutMs: 120000
    crashTaskTimeoutMs: 120000
    patchTaskTimeoutMs: 120000
    confirmedVulnerabilitiesTaskTimeoutMs: 120000
    indexTaskTimeoutMs: 120000
    indexOutputTaskTimeoutMs: 120000
    tracedVulnerabilitiesTaskTimeoutMs: 120000
  # Node-local storage configuration to be accessible by all subcharts
  volumes:
    nodeLocal:
      enabled: true
      hostPath: /node_data_storage
      type: DirectoryOrCreate
      mountPath: /node_data

# Volume configurations
volumes:
  tasks_storage:
    enabled: true
    # When using AKS, specify the appropriate storage class for ReadWriteMany support
    # For example: "azurefile-csi-nfs-${BUTTERCUP_NAMESPACE}"
    storageClass: ""  # Empty string will use cluster default
    size: "5Gi"
    accessMode: ReadWriteMany
  crs_scratch:
    enabled: true
    # When using AKS, specify the appropriate storage class for ReadWriteMany support
    storageClass: ""  # Empty string will use cluster default
    size: "10Gi"
    accessMode: ReadWriteMany
  ui_db:
    enabled: true
    # When using AKS, specify the appropriate storage class for ReadWriteMany support
    storageClass: ""  # Empty string will use cluster default
    size: "1Gi"
    accessMode: ReadWriteOnce


# Dind daemon chart configuration
dind-daemon:
  enabled: true
  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Service-specific configurations
redis:
  image:
    repository: bitnamisecure/redis
    tag: latest
  auth:
    enabled: false  # Disable authentication for simplicity
  architecture: standalone  # Use single instance instead of cluster
  master:
    persistence:
      enabled: true
      size: 8Gi # 8GB of storage for redis, how much is needed?
      storageClass: managed-premium

    configuration: |-
      appendonly yes
      appendfsync everysec
      no-appendfsync-on-rewrite no
      auto-aof-rewrite-percentage 100
      auto-aof-rewrite-min-size 64mb
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  # Add Docker registry authentication
  global:
    imagePullSecrets:
      - ghcr-auth
      - docker-auth

task-server:
  enabled: true
  # API authentication is configured with the following credentials:
  # API Key ID: 515cc8a0-3019-4c9f-8c1c-72d0b54ae561
  # API Token: VGuAC8axfOnFXKBB7irpNDOKcDjOlnyB (for client usage)
  # These values are set in the secret/config-map in config.yaml

task-downloader:
  enabled: true

scheduler:
  enabled: true

program-model:
  enabled: true

build-bot:
  replicaCount: 4
  enabled: true
  timer: 5000
  logLevel: "DEBUG"

fuzzer-bot:
  enabled: true

coverage-bot:
  enabled: true

tracer-bot:
  enabled: true

seed-gen:
  enabled: true
  logMaxLineLength: 10240
  maxCorpusSeedSize: 65536  # 64 KiB

patcher:
  enabled: true

competition-api:
  enabled: true

# Registry cache configuration
registry-cache:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi

# Scratch cleaner configuration
scratch-cleaner:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

# External LiteLLM configuration
litellm:
  endpoint: "http://localhost:4000"  # External LiteLLM endpoint
  apiKey: "sk-BAC316jts53LQF-QHt2cXQ"  # External LiteLLM API key
  bigModel: "${BIG_MODEL}"  # Big model for complex tasks
  smallModel: "${SMALL_MODEL}"  # Small model for simple tasks

# SigNoz observability platform
signoz:
  enabled: false
  clickhouse:
    zookeeper:
      image:
        repository: bitnamilegacy/zookeeper
