{{- if .Values.litellm }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-litellm-api-secrets
  labels:
    app.kubernetes.io/name: litellm-api-secrets
type: Opaque
data:
  # External LiteLLM API key
  BUTTERCUP_LITELLM_KEY: {{ .Values.litellm.apiKey | b64enc | quote }}
{{- end }}
